-- ### S63 CLIENT FUNCTIONS ###
-- Verified on 2026-01-15 

-- ### VISUALS & RENDERING ###
-- Source: LuaInterface.cpp
RenderText(x, y, text, width, sort)
RenderText2(x, y, text, width, sort)
RenderText3(x, y, text, width, sort)
RenderText4(x, y, text, width, sort) -- Added (Impl: RenderText3)
RenderText5(x, y, text, width, sort) -- Added (Impl: RenderText2)
EnableAlphaTest()
DisableAlphaBlend()
glColor3f(r, g, b)
glColor4f(r, g, b, a)
DrawBar(x, y, w, h)
EndDrawBar()
SetFontType(font)
SetTextBg(r, g, b, a)
SetTextColor(r, g, b, a)
GetTextPosY(font, text, y, height)
RenderImage(imageIndex, x, y, w, h)
RenderImage2(Texture, x, y, w, h, u, v, uWidth, vHeight, Scale, StartScale, Alpha)
RenderImage3(Texture, x, y, w, h, u, v, uWidth, vHeight, Alpha)
RenderImageScale(Texture, x, y, w, h, u, v, uWidth, vHeight, Alpha)
RenderImageAuto(Texture, x, y, w, h)
GetImageWidth(texture)
GetImageHeight(texture)
SetBlend(blend)
GLSwitchBlend()
GLSwitch()
-- Source: LuaEffects.cpp
CreateSprite(BMDStruct, Bitmap, Link, Scale, LightR, LightG, LightB, ObjectStruct)
CreateParticle(BMDStruct, Bitmap, SubType, Link, Scale, LightR, LightG, LightB, ObjectStruct)
-- Source: LuaGlobal.cpp
GetWindowWidth()
GetWindowHeight()
GetFontValue()
SetFontValue(value)
GetResolution()
GetVolume()
SetVolume(value)
SetHealthBarSwitch(value)
SetGlowSwitch(value)
SetWingSwitch(value)
getFPS()

-- ### INPUT & WINDOW MANAGEMENT ###
-- Source: LuaInterface.cpp
MousePosX()
MousePosY()
CheckRepeatKey(Key)
CheckPressedKey(Key)
CheckReleasedKey(Key)
CheckWindowOpen(Key)
CloseWindow(Key)
OpenWindow(Key)
ResetMouseL()
ResetMouseR()
ResetMouseM()
WindowGetWidth()
WindowGetWidthAdd()
DisableClickClient()
CheckClickClient()
GetWideX()
SetLockInterfaces()
SetUnlockInterfaces()

-- ### CHARACTER, OBJECTS & ENTITIES ###
-- Source: LuaCharacter.cpp
CharacterGetName(arrayIndex)
CharacterGetIndex(arrayIndex)
CharacterGetIsLive(arrayIndex)
CharacterGetType(arrayIndex)
CharacterGetX(arrayIndex)
CharacterGetY(arrayIndex)
CharacterGetPositionX(arrayIndex)
CharacterGetPositionY(arrayIndex)
CharacterGetPositionZ(arrayIndex)
CharacterGetAngleX(arrayIndex)
CharacterGetAngleY(arrayIndex)
CharacterGetAngleZ(arrayIndex)
CharacterGetHelper(arrayIndex)
CharacterGetWing(arrayIndex)
CharacterGetSword(arrayIndex)
CharacterGetShield(arrayIndex)
CharacterGetHelm(arrayIndex)
CharacterGetArmor(arrayIndex)
CharacterGetPants(arrayIndex)
CharacterGetGloves(arrayIndex)
CharacterGetBoots(arrayIndex)
CharacterGetLevel(arrayIndex)
CharacterGetClass(arrayIndex)
CharacterGetFullClass(arrayIndex)
CharacterGetGuild(arrayIndex)
CharacterGuildGetName(arrayIndex)
CharacterGetGuildStatus(arrayIndex)
CharacterGetVisible(arrayIndex)
CharacterSetAngleX(arrayIndex, value)
CharacterSetAngleY(arrayIndex, value)
CharacterSetAngleZ(arrayIndex, value)
CharacterSetPositionX(arrayIndex, value)
CharacterSetPositionY(arrayIndex, value)
CharacterSetPositionZ(arrayIndex, value)
CharacterSetScale(arrayIndex, value)
SetCharacterAction(arrayIndex, animation)
GetPosFromPlayer(arrayIndex)
FindCharacterStack(index)
GetTargetCharacter()
GetSelectedHero()
SetSelectedHero(value)
SetTargetCharacter(value)
GetClassName(Class)
-- Source: LuaGlobal.cpp
GetMonsterName(Class)

-- ### LOCAL USER & INVENTORY ###
-- Source: LuaUser.cpp
UserGetMap()
UserGetName()
UserGetIndex()
UserPositionX()
UserPositionY()
UserGetHelper()
UserGetWing()
UserGetSword()
UserGetShield()
UserGetHelm()
UserGetArmor()
UserGetPants()
UserGetGloves()
UserGetBoots()
UserGetLevel()
UserGetClass()
UserGetGuild()
GuildGetName()
-- Source: LuaGlobal.cpp
GetNameByIndex(index)
GetCompleteNameByIndex(index, level, exc)
GetWidthByIndex(index)
GetHeightByIndex(index)
GetSlotByIndex(index)
GetInventoryMouseSlot()
GetInventoryMouseItemSlot()
GetInventoryMouseItemIndex()
GetInventoryMouseItemLevel()
GetInventoryMouseItemExc()

-- ### NETWORK & PACKETS ###
-- Source: LuaInterface.cpp
SendMessageClient(text)
SendPlayerChat(text) -- (Registered in LuaCharacter.cpp)
SendTradePlayer(index) -- (Registered in LuaCharacter.cpp)
SendPartyPlayer(index) -- (Registered in LuaCharacter.cpp)
SendGuildPlayer(index) -- (Registered in LuaCharacter.cpp)
SendShopPlayer(index) -- (Registered in LuaCharacter.cpp)
ClientProtocol(head, packetName) -- (Generic Call Event)
-- Source: LuaSocket.cpp
CreatePacket(packetName, head)
SetDwordPacket(packetName, value)
GetDwordPacket(packetName)
SetWordPacket(packetName, value)
GetWordPacket(packetName)
SetBytePacket(packetName, value)
GetBytePacket(packetName)
SetCharPacket(packetName, value)
GetCharPacket(packetName)
SetCharPacketLength(packetName, value, length)
GetCharPacketLength(packetName, length)
SendPacket(packetName)
ClearPacket(packetName) -- (Mapped to GetClearPacket)

-- ### TOOLS, UTILS & PREFS ###
-- Source: LuaInterface.cpp
PlaySound(SoundID)
StopSound(SoundID)
ShowDescriptionComplete(...)
ShowItemDescription(...)
CreateItem(...)
DrawTooltip(x, y, text)
GetLanguage()
-- Source: LuaGlobal.cpp
SetLanguage(lang)
GetGlobalText(index)
GetMapName(map)
GetCountParty()
-- Source: LuaReg.cpp
getValueRegKey(keyValue)
setValueRegKey(keyValue, value)
getStringRegKey(keyValue, keySize)
setStringRegKey(keyValue, value)
